config/routes.rb
Rails.application.routes.draw do
  root "movies#index"

  resources :genres
  resources :users

  get "signup" => "users#new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
  # Defines the root path route ("/")

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>  <div class="flash notice">    <%= flash[:notice] %>  </div><% end %><% if flash[:alert] %>  <div class="flash alert">    <%= flash[:alert] %>  </div><% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<header>
  <nav>
    <%= image_tag("logo.png") %>
    <ul class="left">
      <li>
        <%= link_to "Released", movies_path %>
      </li>
      <li>
        <%= link_to 'Upcoming', filtered_movies_path(:upcoming) %>
      </li>
      <li>
        <%= link_to 'Recent', filtered_movies_path(:recent) %>
      </li>
      <li>
        <%= link_to "Hits", filtered_movies_path(:hits) %>
      </li>
      <li>
        <%= link_to "Flops", filtered_movies_path(:flops) %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Account Settings", edit_user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Sign Out", session_path,
                      data: { turbo_method: :delete },
                      class: "button" %>
      <% else %>
        <li>
          <%= link_to "Sign In", signin_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

<div class="content">
  <%= render "layouts/flash" %>

  <%= yield %>
</div>
</body>
</html>